version: "3.8"

services:
  postgres:
    image: postgres:18
    container_name: challenge-postgres
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: postgres
      POSTGRESS_PASSWORD: 23112017
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: challenge-app
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/challenge
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 23112017
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

volumes:
  postgres_data: